# File: crates/materials-eco-knowledge-labeller/Cargo.toml
[package]
name = "materials-eco-knowledge-labeller"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = { version = "1.0.120" }
clap = { version = "4.5.4", features = ["derive"] }
regex = "1.10.5"
thiserror = "1.0.63"

[[bin]]
name = "materials-eco-knowledge-labeler"
path = "src/bin/labeler.rs"
