// Filename: crates/ecosafety_design_authorship/src/lib.rs
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Serialize, Deserialize)]
pub enum Domain {
    Cyboquatic,
    Cybocinder,
    Biopack,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DesignAuthorshipParticle {
    pub designkernelid: String,
    pub designversion: String,
    pub designauthorid: String,
    pub domain: Domain,

    pub ker_K: f64,
    pub ker_E: f64,
    pub ker_R: f64,

    pub ncorridors: u32,
    pub nverifiedinvariants: u32,

    pub kani_proof_hashes: Vec<String>,
    pub repo_path: String,
    pub commit_hash: String,
    pub ecosafety_core_dep: String,
    pub evidencehex: String,
}

impl DesignAuthorshipParticle {
    pub fn ker_bounds_ok(&self) -> bool {
        self.ker_K >= 0.80 && self.ker_K <= 1.00 &&
        self.ker_E >= 0.80 && self.ker_E <= 1.00 &&
        self.ker_R >= 0.0  && self.ker_R <= 0.50
    }

    pub fn author_did_ok(&self) -> bool {
        self.designauthorid.starts_with("bostrom")
            && self.designauthorid.len() >= 10
    }

    pub fn kani_proofs_nonempty(&self) -> bool {
        !self.kani_proof_hashes.is_empty()
    }

    pub fn invariants_nonnegative(&self) -> bool {
        self.nverifiedinvariants >= 0 && self.ncorridors >= 0
    }
}

// This manifest would be generated by CI from all Kani harnesses in the mono-repo.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct KaniManifest {
    pub crate_name: String,
    pub repo_path: String,
    pub commit_hash: String,
    pub proof_hashes: Vec<String>,
}

pub fn validate_design_authorship_particle(
    particle: &DesignAuthorshipParticle,
    manifest: &KaniManifest,
) -> bool {
    if !particle.ker_bounds_ok() { return false; }
    if !particle.author_did_ok() { return false; }
    if !particle.kani_proofs_nonempty() { return false; }
    if !particle.invariants_nonnegative() { return false; }

    if particle.repo_path != manifest.repo_path {
        return false;
    }
    if particle.commit_hash != manifest.commit_hash {
        return false;
    }

    // All declared proof hashes must be present in manifest.
    for h in &particle.kani_proof_hashes {
        if !manifest.proof_hashes.iter().any(|mh| mh == h) {
            return false;
        }
    }

    true
}
