-- filename: eco_restoration_shard/cyboquatic_progress/ai_datacenter_governance/sql/daily_progress_ai_node.sql

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS daily_progress_ai_node (
    nodeid                    TEXT    NOT NULL,
    region                    TEXT    NOT NULL,
    lane                      TEXT    NOT NULL,
    steward_uuid              TEXT    NOT NULL,
    steward_signinghex        TEXT    NOT NULL,
    yyyymmdd                  TEXT    NOT NULL,
    twindow_start             TEXT    NOT NULL,
    twindow_end               TEXT    NOT NULL,

    core_energy_kwh_per_workload REAL NOT NULL CHECK(core_energy_kwh_per_workload >= 0.0),
    joules_per_inference          REAL NOT NULL CHECK(joules_per_inference >= 0.0),
    pue                           REAL NOT NULL CHECK(pue >= 0.0),
    cue_kg_co2_per_kwh            REAL NOT NULL CHECK(cue_kg_co2_per_kwh >= 0.0),
    eco_per_joule                 REAL NOT NULL,
    throughput_tokens_per_s       REAL NOT NULL,
    throughput_inferences_per_s   REAL NOT NULL,
    utilization_pct               REAL NOT NULL CHECK(utilization_pct >= 0.0 AND utilization_pct <= 100.0),
    ere                           REAL NOT NULL,
    eco_task_ratio_pct            REAL NOT NULL,
    wue_l_per_kwh                 REAL NOT NULL CHECK(wue_l_per_kwh >= 0.0),
    embodied_kg_co2eq             REAL NOT NULL CHECK(embodied_kg_co2eq >= 0.0),
    topology_violation_count      INTEGER NOT NULL CHECK(topology_violation_count >= 0),

    r_pue             REAL NOT NULL CHECK(r_pue             >= 0.0 AND r_pue             <= 1.0),
    r_cue             REAL NOT NULL CHECK(r_cue             >= 0.0 AND r_cue             <= 1.0),
    r_eco_per_joule   REAL NOT NULL CHECK(r_eco_per_joule   >= 0.0 AND r_eco_per_joule   <= 1.0),
    r_eco_task_ratio  REAL NOT NULL CHECK(r_eco_task_ratio  >= 0.0 AND r_eco_task_ratio  <= 1.0),
    r_wue             REAL NOT NULL CHECK(r_wue             >= 0.0 AND r_wue             <= 1.0),
    r_embodied        REAL NOT NULL CHECK(r_embodied        >= 0.0 AND r_embodied        <= 1.0),
    r_topology        REAL NOT NULL CHECK(r_topology        >= 0.0 AND r_topology        <= 1.0),
    r_energy          REAL NOT NULL CHECK(r_energy          >= 0.0 AND r_energy          <= 1.0),
    r_joule_inf       REAL NOT NULL CHECK(r_joule_inf       >= 0.0 AND r_joule_inf       <= 1.0),
    r_heat_reuse      REAL NOT NULL CHECK(r_heat_reuse      >= 0.0 AND r_heat_reuse      <= 1.0),
    r_utilization     REAL NOT NULL CHECK(r_utilization     >= 0.0 AND r_utilization     <= 1.0),
    r_bandwidth       REAL NOT NULL CHECK(r_bandwidth       >= 0.0 AND r_bandwidth       <= 1.0),

    vt                REAL NOT NULL CHECK(vt >= 0.0),
    k                 REAL NOT NULL CHECK(k  >= 0.0 AND k  <= 1.0),
    e                 REAL NOT NULL CHECK(e  >= 0.0 AND e  <= 1.0),
    r                 REAL NOT NULL CHECK(r  >= 0.0 AND r  <= 1.0),

    strength_index_s  REAL NOT NULL CHECK(strength_index_s >= 0.0 AND strength_index_s <= 1.0),

    evidencehex       TEXT    NOT NULL,
    prior_evidencehex TEXT,
    phoenix_anchor_id TEXT,
    created_utc       TEXT    NOT NULL,

    PRIMARY KEY (nodeid, yyyymmdd)
);

CREATE INDEX IF NOT EXISTS idx_daily_ai_node_lane_time
    ON daily_progress_ai_node (lane, yyyymmdd);

CREATE INDEX IF NOT EXISTS idx_daily_ai_node_steward_time
    ON daily_progress_ai_node (steward_uuid, yyyymmdd);

CREATE INDEX IF NOT EXISTS idx_daily_ai_node_evidence
    ON daily_progress_ai_node (evidencehex);

INSERT OR IGNORE INTO daily_progress_ai_node (
    nodeid,
    region,
    lane,
    steward_uuid,
    steward_signinghex,
    yyyymmdd,
    twindow_start,
    twindow_end,
    core_energy_kwh_per_workload,
    joules_per_inference,
    pue,
    cue_kg_co2_per_kwh,
    eco_per_joule,
    throughput_tokens_per_s,
    throughput_inferences_per_s,
    utilization_pct,
    ere,
    eco_task_ratio_pct,
    wue_l_per_kwh,
    embodied_kg_co2eq,
    topology_violation_count,
    r_pue,
    r_cue,
    r_eco_per_joule,
    r_eco_task_ratio,
    r_wue,
    r_embodied,
    r_topology,
    r_energy,
    r_joule_inf,
    r_heat_reuse,
    r_utilization,
    r_bandwidth,
    vt,
    k,
    e,
    r,
    strength_index_s,
    evidencehex,
    prior_evidencehex,
    phoenix_anchor_id,
    created_utc
) VALUES (
    'PHX-AI-DC-01',
    'Phoenix-AZ',
    'RESEARCH',
    '87cb8e02-c918-4b2a-aa40-36a8efa37e52',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    '20260716',
    '2026-07-16T00:00:00Z',
    '2026-07-16T23:59:59Z',
    0.25,
    3.5,
    1.15,
    0.20,
    0.80,
    1200.0,
    35.0,
    76.0,
    0.10,
    0.65,
    0.90,
    15.0,
    0,
    0.25,
    0.30,
    0.20,
    0.20,
    0.25,
    0.15,
    0.00,
    0.15,
    0.20,
    0.10,
    0.0,
    0.0,
    0.42,
    0.93,
    0.91,
    0.13,
    0.88,
    '0x20260716PHXAIDCNODE01SEED',
    NULL,
    '0x20260716PHXAIDCGOVFRAMEWORKV1',
    '2026-07-16T00:00:00Z'
);
