-- filename: insert_tasks_monorepo_consolidation.sql
-- destination: eco_restoration_shard/db/insert_tasks_monorepo_consolidation.sql
-- repo-target: github.com/mk-bluebird/eco_restoration_shard

PRAGMA foreign_keys = ON;

INSERT INTO monorepo_task (
    category,
    scope,
    title,
    description,
    repo_target,
    file_path,
    status,
    priority,
    depends_on,
    logicalname,
    author_bostrom,
    createdutc,
    updatedutc
) VALUES
(
    'GOVERNANCE_DB',
    'PHOENIX-AZ',
    'Register eco_restoration_shard repo and files in repo/repofile index',
    'Create db_repo_index.sql and ensure every governance-relevant file in eco_restoration_shard is registered in repo and repofile tables with purpose and language metadata for Phoenix-AZ.',
    'github.com/mk-bluebird/eco_restoration_shard',
    'db/db_repo_index.sql',
    'OPEN',
    'HIGH',
    NULL,
    'restoration.repoindex.phoenix',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    datetime('now'),
    datetime('now')
),
(
    'GOVERNANCE_DB',
    'PHOENIX-AZ',
    'Create local DefinitionRegistry slice for restoration artifacts',
    'Implement db_definition_registry_restoration.sql with definitionregistry_restoration table and register all Phoenix restoration/energy/MT6883 SQL, ALN, and tool artifacts with logicalnames and hashes.',
    'github.com/mk-bluebird/eco_restoration_shard',
    'db/db_definition_registry_restoration.sql',
    'OPEN',
    'HIGH',
    'restoration.repoindex.phoenix',
    'restoration.definitionregistry.phoenix',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    datetime('now'),
    datetime('now')
),
(
    'GOVERNANCE_DB',
    'PHOENIX-AZ',
    'Finalize restoration-aware blastradius grammar for Phoenix',
    'Complete db_restoration_blastradius_phoenix.sql to extend blastradiusindex with restorationradius, deltamass_window_kg, deltakarma_window, gw_risk_max, restoration_ok, and author metadata, plus Phoenix-scoped views v_blastradius_restoration_phx and v_restoration_nodes_phx.',
    'github.com/mk-bluebird/eco_restoration_shard',
    'db/db_restoration_blastradius_phoenix.sql',
    'OPEN',
    'HIGH',
    'restoration.definitionregistry.phoenix',
    'restoration.blastradius.phoenix.2026v1',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    datetime('now'),
    datetime('now')
),
(
    'GOVERNANCE_DB',
    'PHOENIX-AZ',
    'Finalize eco-per-joule policy grammar for Phoenix energy planes',
    'Implement db_ecoperjoule_policy_energy.sql and register ecoperjoule_policy, v_cyboquatic_ecoperjoule, and v_cyboquatic_ecoperjoule_prod_phx under a DefinitionRegistry entry energy.ecoperjoule.policy.phoenix.2026v1.',
    'github.com/mk-bluebird/eco_restoration_shard',
    'db/db_ecoperjoule_policy_energy.sql',
    'OPEN',
    'HIGH',
    'restoration.definitionregistry.phoenix',
    'energy.ecoperjoule.policy.phoenix.2026v1',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    datetime('now'),
    datetime('now')
),
(
    'GOVERNANCE_DB',
    'PHOENIX-AZ',
    'Integrate MT6883 continuity and neuroethic radii into lane and blast grammar',
    'Extend lanestatusshard and blastradiusindex via db_mt6883_lane_continuity.sql with mt6883_ok, neuroethic_radius_hours, neuroethic_ok, and related views v_mt6883_lane_continuity and v_blastradius_mt6883_neuro under logicalname mt6883.lane.continuity.phoenix.2026v1.',
    'github.com/mk-bluebird/eco_restoration_shard',
    'db/db_mt6883_lane_continuity.sql',
    'OPEN',
    'HIGH',
    'restoration.definitionregistry.phoenix',
    'mt6883.lane.continuity.phoenix.2026v1',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    datetime('now'),
    datetime('now')
),
(
    'GOVERNANCE_DB',
    'PHOENIX-AZ',
    'Populate restoration_identity_binding for all Phoenix governance artifacts',
    'Fill restoration_identity_binding with rows binding bostrom18sd...ye7 to restorationindex.sqlite3, blastradius, ecoperjoule, MT6883, and tooling files, ensuring region=Phoenix-AZ, scope=REGION, dbrole=GOVERNANCE.',
    'github.com/mk-bluebird/eco_restoration_shard',
    'db/db_restoration_identity_binding.sql',
    'OPEN',
    'HIGH',
    'restoration.definitionregistry.phoenix',
    'restoration.identitybinding.phoenix.2026v1',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    datetime('now'),
    datetime('now')
),
(
    'TOOLING',
    'PHOENIX-AZ',
    'Harden non-actuating C++ governance tool for restoration, energy, and MT6883',
    'Complete src/tools/restoration_energy_mt6883_tool.cpp to query v_active_restoration_contracts_primary, v_prod_eligible_restoration_planes, v_cyboquatic_ecoperjoule_prod_phx, and v_mt6883_lane_continuity with robust error handling and CI-ready output.',
    'github.com/mk-bluebird/eco_restoration_shard',
    'src/tools/restoration_energy_mt6883_tool.cpp',
    'OPEN',
    'HIGH',
    'restoration.identitybinding.phoenix.2026v1',
    'restoration.energy.mt6883.tool.cpp.phoenix',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    datetime('now'),
    datetime('now')
),
(
    'TOOLING',
    'PHOENIX-AZ',
    'Add JSON output mode to C++ governance tool',
    'Extend restoration_energy_mt6883_tool.cpp with a --format=json flag that emits machine-readable JSON for all supported queries, maintaining non-actuating behavior and consistent field naming.',
    'github.com/mk-bluebird/eco_restoration_shard',
    'src/tools/restoration_energy_mt6883_tool.cpp',
    'OPEN',
    'MEDIUM',
    'restoration.energy.mt6883.tool.cpp.phoenix',
    'restoration.energy.mt6883.tool.cpp.jsonmode',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    datetime('now'),
    datetime('now')
),
(
    'TOOLING',
    'GLOBAL_PATTERN',
    'Create Rust governance spine client for eco_restoration_shard',
    'Implement a Rust crate within eco_restoration_shard that wraps restorationindex.sqlite3 via rusqlite, exposing typed accessors for KER, blastradius, ecoperjoule, MT6883, and identity bindings for cross-repo CI and agents.',
    'github.com/mk-bluebird/eco_restoration_shard',
    'src/lib/governance_spine_client.rs',
    'OPEN',
    'HIGH',
    'restoration.definitionregistry.phoenix',
    'restoration.governance.spine.client.rust',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    datetime('now'),
    datetime('now')
),
(
    'CI',
    'CONSTELLATION',
    'Enforce DefinitionRegistry registration for all governance artifacts',
    'Add CI scripts that query definitionregistry_restoration and fail builds if new SQL/ALN/Rust governance files are not registered with logicalnames and hashes, consolidating all constellational functions into the monorepo registry.',
    'github.com/mk-bluebird/eco_restoration_shard',
    '.github/workflows/ci_definitionregistry.yml',
    'OPEN',
    'HIGH',
    'restoration.definitionregistry.phoenix',
    'ci.definitionregistry.enforcement.phoenix',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    datetime('now'),
    datetime('now')
),
(
    'CI',
    'CONSTELLATION',
    'Enforce identity bindings for governance artifacts',
    'Add CI checks that require every governance artifact to have a corresponding restoration_identity_binding row, rejecting anonymous or unbound changes and centralizing identity governance in eco_restoration_shard.',
    'github.com/mk-bluebird/eco_restoration_shard',
    '.github/workflows/ci_identity_binding.yml',
    'OPEN',
    'HIGH',
    'restoration.identitybinding.phoenix.2026v1',
    'ci.identitybinding.enforcement.phoenix',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    datetime('now'),
    datetime('now')
),
(
    'AGENT_API',
    'CONSTELLATION',
    'Publish agent-facing governance views for Phoenix',
    'Create agent-oriented views (e.g., v_agent_restoration_nodes_phx, v_agent_ecoperjoule_phx, v_agent_mt6883_continuity_phx) that present KER, lanes, blast radius, ecoperjoule, and continuity in stable schemas for AI agents.',
    'github.com/mk-bluebird/eco_restoration_shard',
    'db/db_agent_views_phoenix.sql',
    'OPEN',
    'MEDIUM',
    'restoration.blastradius.phoenix.2026v1,energy.ecoperjoule.policy.phoenix.2026v1,mt6883.lane.continuity.phoenix.2026v1',
    'agent.views.phoenix.2026v1',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    datetime('now'),
    datetime('now')
),
(
    'DOCS',
    'CONSTELLATION',
    'Author monorepo governance blueprint documentation',
    'Create a markdown document that explains how eco_restoration_shard consolidates restoration, energy, and MT6883 governance functions for the constellation, including registry usage, shard catalog, identity bindings, and tooling interfaces.',
    'github.com/mk-bluebird/eco_restoration_shard',
    'docs/monorepo_governance_blueprint.md',
    'OPEN',
    'MEDIUM',
    'restoration.definitionregistry.phoenix,restoration.identitybinding.phoenix.2026v1',
    'docs.monorepo.governance.blueprint',
    'bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7',
    datetime('now'),
    datetime('now')
);
