-- File: eco_restoration_shard/cyboquatic_progress/20260713/sql/cyboquatic_workload_energy_telemetry_20260713.sql
-- Domain: (d) Cyboquatic workload (energyreqJ, ΔVt) with SQL telemetry.
-- Purpose: Provide a production-ready SQLite schema and helper views for inserting and querying
--          cyboquatic workload telemetry generated by CyboquaticWorkloadEnergyTelemetry.kt.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS workload_daily_progress (
    progress_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    yyyymmdd          TEXT    NOT NULL,
    domain            TEXT    NOT NULL,
    subtask_id        TEXT    NOT NULL,
    node_id           TEXT    NOT NULL,
    sample_id         TEXT    NOT NULL,
    timestamp_utc     TEXT    NOT NULL,
    energy_req_j      REAL    NOT NULL,
    energy_surplus_j  REAL    NOT NULL,
    hydraulic_risk    REAL    NOT NULL,
    uncertainty_risk  REAL    NOT NULL,
    renergy           REAL    NOT NULL,
    rhydraulic        REAL    NOT NULL,
    runcertainty      REAL    NOT NULL,
    vt_before         REAL    NOT NULL,
    vt_after          REAL    NOT NULL,
    delta_vt          REAL    NOT NULL,
    k_factor          REAL    NOT NULL,
    e_factor          REAL    NOT NULL,
    r_factor          REAL    NOT NULL,
    phoenix_hex       TEXT    NOT NULL,
    prior_pointer     TEXT    NOT NULL,
    created_at        TEXT    NOT NULL DEFAULT (datetime('now','localtime'))
);

CREATE INDEX IF NOT EXISTS idx_workload_daily_date
    ON workload_daily_progress (yyyymmdd);

CREATE INDEX IF NOT EXISTS idx_workload_daily_node_time
    ON workload_daily_progress (node_id, timestamp_utc);

CREATE INDEX IF NOT EXISTS idx_workload_daily_domain_subtask
    ON workload_daily_progress (domain, subtask_id);

CREATE VIEW IF NOT EXISTS workload_daily_summary AS
SELECT
    yyyymmdd,
    domain,
    subtask_id,
    COUNT(*)                      AS sample_count,
    AVG(energy_req_j)             AS avg_energy_req_j,
    AVG(energy_surplus_j)         AS avg_energy_surplus_j,
    AVG(hydraulic_risk)           AS avg_hydraulic_risk,
    AVG(uncertainty_risk)         AS avg_uncertainty_risk,
    AVG(renergy)                  AS avg_renergy,
    AVG(rhydraulic)               AS avg_rhydraulic,
    AVG(runcertainty)             AS avg_runcertainty,
    AVG(vt_before)                AS avg_vt_before,
    AVG(vt_after)                 AS avg_vt_after,
    AVG(delta_vt)                 AS avg_delta_vt,
    AVG(k_factor)                 AS avg_k_factor,
    AVG(e_factor)                 AS avg_e_factor,
    AVG(r_factor)                 AS avg_r_factor
FROM workload_daily_progress
GROUP BY yyyymmdd, domain, subtask_id;

CREATE VIEW IF NOT EXISTS workload_high_risk_samples AS
SELECT
    progress_id,
    yyyymmdd,
    node_id,
    sample_id,
    timestamp_utc,
    r_factor,
    renergy,
    rhydraulic,
    runcertainty,
    vt_after,
    delta_vt
FROM workload_daily_progress
WHERE r_factor >= 0.7
ORDER BY timestamp_utc ASC;
