// filename: crates/bostrom-signer/src/lib.rs
// destination: ecorestorationshard/crates/bostrom-signer/src/lib.rs

use std::error::Error as StdError;
use std::fmt;

use cosmos_sdk_proto::prost::Message;
use cosmos_sdk_proto::traits::Message as CosmosMessage;
use tendermint::crypto::Ed25519PublicKey;

const PRIMARY_CONTRIBUTOR_ADDRESS: &str = "bostrom18sd2ujv24ual9c9pshtxys6j8knh6xaead9ye7";
const MSG_CONTRIBUTE_RESEARCH_ARTIFACT_TYPE: &str =
    "/bostrom.eco.v1.MsgContributeResearchArtifact";

#[derive(Debug)]
pub enum SignError {
    UnsupportedMessageType(String),
    InvalidContributorAddress {
        expected: String,
        found: String,
    },
    EncodingError(String),
    CryptoError(String),
}

impl fmt::Display for SignError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SignError::UnsupportedMessageType(t) => {
                write!(f, "unsupported message type for signer: {}", t)
            }
            SignError::InvalidContributorAddress { expected, found } => {
                write!(
                    f,
                    "invalid contributor_address: expected {}, found {}",
                    expected, found
                )
            }
            SignError::EncodingError(e) => write!(f, "encoding error: {}", e),
            SignError::CryptoError(e) => write!(f, "crypto error: {}", e),
        }
    }
}

impl StdError for SignError {}

/// Core signer trait used by bostrom-signer.
pub trait Signer {
    fn public_key(&self) -> &Ed25519PublicKey;

    /// Sign a Cosmos SDK message with enforced contributor_address policy.
    ///
    /// - If msg type is MsgContributeResearchArtifact, this method rewrites
    ///   contributor_address to PRIMARY_CONTRIBUTOR_ADDRESS.
    /// - If the message already contains a different contributor_address, the
    ///   method refuses to sign and returns SignError::InvalidContributorAddress.
    fn sign(&self, msg_any: &mut cosmos_sdk_proto::Any) -> Result<Vec<u8>, SignError>;
}

/// Concrete signer implementation using an Ed25519 private key.
pub struct Ed25519Signer {
    pk: Ed25519PublicKey,
    sk: ed25519_dalek::SigningKey,
}

impl Ed25519Signer {
    pub fn new(pk: Ed25519PublicKey, sk: ed25519_dalek::SigningKey) -> Self {
        Self { pk, sk }
    }

    fn sign_bytes(&self, bytes: &[u8]) -> Result<Vec<u8>, SignError> {
        use ed25519_dalek::Signer;
        let signature = self
            .sk
            .try_sign(bytes)
            .map_err(|e| SignError::CryptoError(e.to_string()))?;
        Ok(signature.to_bytes().to_vec())
    }
}

impl Signer for Ed25519Signer {
    fn public_key(&self) -> &Ed25519PublicKey {
        &self.pk
    }

    fn sign(&self, msg_any: &mut cosmos_sdk_proto::Any) -> Result<Vec<u8>, SignError> {
        // Only enforce contributor_address for MsgContributeResearchArtifact.
        if msg_any.type_url == MSG_CONTRIBUTE_RESEARCH_ARTIFACT_TYPE {
            // Decode the concrete message.
            let mut msg = MsgContributeResearchArtifact::decode(msg_any.value.as_slice())
                .map_err(|e| SignError::EncodingError(e.to_string()))?;

            // If contributor_address is set and differs from the primary address, refuse to sign.
            if !msg.contributor_address.is_empty()
                && msg.contributor_address != PRIMARY_CONTRIBUTOR_ADDRESS
            {
                return Err(SignError::InvalidContributorAddress {
                    expected: PRIMARY_CONTRIBUTOR_ADDRESS.to_string(),
                    found: msg.contributor_address.clone(),
                });
            }

            // Force contributor_address to the primary Bostrom address.
            msg.contributor_address = PRIMARY_CONTRIBUTOR_ADDRESS.to_string();

            // Re-encode into Any.
            let mut buf = Vec::with_capacity(msg.encoded_len());
            msg.encode(&mut buf)
                .map_err(|e| SignError::EncodingError(e.to_string()))?;
            msg_any.value = buf;
        }

        // Serialize the Any as the sign bytes.
        let mut sign_bytes = Vec::with_capacity(msg_any.encoded_len());
        msg_any
            .encode(&mut sign_bytes)
            .map_err(|e| SignError::EncodingError(e.to_string()))?;

        // Produce signature.
        self.sign_bytes(&sign_bytes)
    }
}

// -----------------------------------------------------------------------------
// MsgContributeResearchArtifact proto binding
// -----------------------------------------------------------------------------

// Generated protobuf binding for MsgContributeResearchArtifact.
// This struct should be generated by prost from your .proto file and imported
// from the appropriate crate/module. Shown here explicitly for clarity.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgContributeResearchArtifact {
    #[prost(string, tag = "1")]
    pub artifact_cid: String,
    #[prost(string, tag = "2")]
    pub artifact_type: String,
    #[prost(string, tag = "3")]
    pub contributor_address: String,
    #[prost(string, tag = "4")]
    pub payload_hash: String,
    #[prost(string, tag = "5")]
    pub evidence_cid: String,
}
